site_name: 0xsmft
repo_url: https://github.com/0xsmft/Saturn-Engine
repo_name: 0xsmft/Saturn-Engine
copyright: Website version 1.3.1-A61fOS
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - content.code.annotate
    - content.code.copy
    - content.tooltips
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/0xsmft
  generator: true
plugins:
  - awesome-nav
  - search
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
markdown_extensions:
  - admonition