site_name: 0xsmft
repo_url: https://github.com/0xsmft/Saturn-Engine
repo_name: 0xsmft/Saturn-Engine
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer
    - navigation.sections
    - navigation.expand
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/0xsmft
  generator: false
plugins:
  - awesome-nav
  - git-revision-date-localized:
      type: date